name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      placeholder: Clear bug description
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1) Go to...
        2) Click...
        3) Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - frontend
        - backend
        - ci/cd
        - infra
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste stack trace, API response, screenshots